format = """
[](#002b36)\
$username\
$hostname\
[](fg:#002b36 bg:#268bd2)\
$directory\
[](fg:#268bd2 bg:#859900)\
$git_branch\
$git_status\
[ ](fg:#859900)
"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#002b36 fg:#b58900"
format = '[$user]($style)'
disabled = false

[hostname]
ssh_only = false 
style = "bg:#002b36 fg:#b58900"
format = "[@$ssh_symbol$hostname ]($style)"

[directory]
style = "bg:#268bd2 fg:#002b36"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "bg:#859900 fg:#002b36"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#859900 fg:#002b36"
format = '[$all_status$ahead_behind]($style)'

